#!/bin/bash

TFE="/Applications/Torrent\ File\ Editor.app/Contents/MacOS/Torrent\ File\ Editor"
TMPJSON=$(mktemp)
BASEDIR="tfefix"


for TORRENTFILE in $@
do
  eval $TFE --to-json $TORRENTFILE $TMPJSON

  NAME=$(jq -r ".info.name" $TMPJSON)
  ANNOUNCE=$(jq -r ".announce" $TMPJSON)

#  ANNOUNCE=$(echo $ANNOUNCE | grep -o '\:[^$]*\:' | tr -d ':')
#  ANNOUNCE="${ANNOUNCE:2}"

  ANNOUNCE=$(echo $ANNOUNCE | awk -F/ '{print $3}')
  if [ -z "$ANNOUNCE" ]; then
    ANNOUNCE="noannounce"
  fi
  echo "${TORRENTFILE} => ${NAME}"
  DIR="${BASEDIR}"

  if [ -n "$ANNOUNCE" ]; then
    DIR="${BASEDIR}/${ANNOUNCE}"
  fi

  mkdir -p "$DIR"
  cp "$TORRENTFILE" "${DIR}/${NAME}.torrent"
#  cat  $TMPJSON

  rm $TMPJSON
done
